[package]
name = "lasso"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-poly = "0.5"
ark-poly-commit = "0.5"
ark-ff = "0.5"
ark-bn254 = "0.5"
# ark-sponge = { version = "0.4", features = ["sha3"] }
rand = "0.8"
ark-pallas = "0.5.0"
anyhow = "1.0.100"
ark-crypto-primitives = "0.5.0"
